apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-tech-movag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-tech-movag
  template:
    metadata:
      labels:
        app: stock-tech-movag
    spec:
      containers:
        - name: stock-tech-movag
          image: your-registry/stock-tech-movag:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: RABBITMQ_HOST
              value: "stock-tech-movag-rabbitmq.dev.internal"
            - name: RABBITMQ_QUEUE
              value: "stock-tech-movag_dev_queue"
